// Code generated by "stringer -type=SectionType"; DO NOT EDIT.

package gid

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Standard-1]
	_ = x[Default-2]
	_ = x[Prefix-3]
	_ = x[NewLine-4]
	_ = x[Comment-5]
}

const _SectionType_name = "StandardDefaultPrefixNewLineComment"

var _SectionType_index = [...]uint8{0, 8, 15, 21, 28, 35}

func (i SectionType) String() string {
	i -= 1
	if i < 0 || i >= SectionType(len(_SectionType_index)-1) {
		return "SectionType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _SectionType_name[_SectionType_index[i]:_SectionType_index[i+1]]
}
